### PR TITLE
Fetch + inline remote image URLs at the gateway (vision models)

### PR DESCRIPTION
**Pull request by RezaRahemtola**
## Problem

Vision requests with a remote `image_url` (e.g. `https://…/pic.png`) returned `503 "All servers unavailable"` while base64 data URLs worked. Root cause: vLLM fetches remote media itself with a bot-bare UA (`vLLM/<ver>`), hosts like `upload.wikimedia.org` rate-limit it (429), vLLM turns any fetch failure into HTTP 500, and the libertai-api router masks upstream 5xx as 503 — with each failover re-fetching the URL and worsening the rate limit. vLLM has no URL cache, no UA config, and upstream won't fix the error semantics (vllm#21254 stale-closed, vllm#47163 ignored).

## Change

The gateway now downloads remote image URLs itself and rewrites them to base64 before forwarding to vLLM, so vLLM never sees a URL. New self-contained module `src/image_fetch.py`; ~18 lines wired into `src/proxy.py`'s `proxy_request` (after the `allowed_paths` gate, before the `stream_options` block).

- **SSRF-safe fetcher** — resolve host → reject if *any* resolved IP isn't public (`ipv4_mapped` unwrap is load-bearing on the boxes' Python 3.11.2) → pin the socket to the validated IP while keeping SNI/cert verification on the real hostname → re-validate on every redirect hop (≤3). One `asyncio.timeout(10)` wall-clock bound, 10 MB cap enforced mid-stream, magic-byte type check (PNG/JPEG/GIF/WebP), `LibertAI/1.0` UA, own request headers (never forwards caller auth). Keep-alive disabled to prevent cross-host TLS reuse on shared IPs.
- **In-process cache** — 64 MB LRU (base64 strings), 10 min TTL, in-flight dedup via a detached shielded fetch, split negative-cache TTLs.
- **Three request formats** — OpenAI chat, OpenAI responses, Anthropic. ≤4 distinct URLs/request (matches vLLM `--limit-mm-per-prompt {"image":4}`); every occurrence rewritten.
- **Failure taxonomy** — fetch/validation failures → clean `400` (router passes 4xx through without failover); any unexpected bug → forward body **unmodified**, never 500. This is the core fix for the original 503.
- `stream_options`/`include_usage` injection stays gated to the OpenAI paths only.

## Tests

65 passing (`src/image_fetch.py` unit-tested end to end incl. SSRF table, redirect/rebinding, cache/dedup, magic bytes; `proxy_request` integration test via TestClient + MockTransport). CI (ruff + mypy) green.

## Verified in production

Deployed to all active vision replicas (qwen3.6-27b ×2, qwen3.5-122b-a10b, qwen3.6-35b-a3b ×2). On each: remote wikimedia URL → 200, SSRF (`169.254.169.254` / `127.0.0.1`) → 400, base64 regression → 200, and `api.libertai.io` repro returns 200 consistently.

Design/plan: `docs/superpowers/specs/2026-07-16-image-url-fetch-design.md`, `docs/superpowers/plans/2026-07-16-image-url-fetch.md` (uncommitted).

### CODE REVIEW

**Review by foxpatch-aleph — COMMENTED** [review]
Well-designed SSRF-safe image URL fetcher with thorough test coverage. The core security model (IP pinning, redirect re-validation, magic-byte type checking, size cap) is sound. The error taxonomy (400 for fetch failures, pass-through for unexpected errors) correctly addresses the original 503 issue. Non-blocking observations: use asyncio.get_running_loop() instead of get_event_loop() for consistency with the rest of the codebase; _collect_image_parts is vulnerable to RecursionError on deeply nested JSON (safely caught but reverts to the original problem for that request); one test is convoluted with redundant patches; integration tests only cover the OpenAI chat path, not Anthropic or OpenAI Responses paths.

**`src/image_fetch.py`** (line 116): Use `asyncio.get_running_loop()` instead of `asyncio.get_event_loop()` here and in lines 231, 245, 262, 279. The existing codebase (src/image_routes.py, src/tts_routes.py) consistently uses `get_running_loop()`. While `get_event_loop()` works in async context, `get_running_loop()` is the modern API and raises immediately if called outside a running loop.

**`src/image_fetch.py`** (line 66): `_collect_image_parts` uses Python recursion to walk the JSON tree. A deeply nested body (~500 levels) that `json.loads` can parse would cause `RecursionError` here. The proxy catches this and forwards unmodified, which is safe but reverts to the original 503 problem for that request. Could add a depth limit or use an iterative walk.

**`tests/test_image_fetch.py`** (line 135): This test patches `getaddrinfo` redundantly — line 135 patches `imgf.asyncio.get_event_loop().getaddrinfo`, line 136 is a no-op (patches `_resolve_public_ips` with itself), and lines 139-140 patch the loop's `getaddrinfo` again. Lines 135-136 can be removed.

**`tests/test_proxy_image_inline.py`** (line 37): All three integration tests use `v1/chat/completions`. Consider adding at least one test for `v1/messages` (Anthropic) or `v1/responses` (OpenAI Responses) to verify the proxy wiring works end-to-end for those formats.

**`pyproject.toml`** (line 55): File is missing a trailing newline (confirmed in the diff).

**Review by foxpatch-aleph — COMMENTED** [review]
Well-designed SSRF-safe image inlining module with thorough test coverage. The SSRF mitigations (IP pinning with SNI, per-redirect re-validation, IPv4-mapped unwrap) are correct and robust. The cache/dedup layer is well-implemented. The failure taxonomy (400 for fetch errors, pass-through for unexpected bugs) correctly addresses the original 503 failover loop. One real issue: `asyncio.timeout()` requires Python 3.11+ but `pyproject.toml` declares `>=3.10`, which would cause an `AttributeError` on 3.10. Minor nits: dead code in a test, deprecated `get_event_loop()` usage, and a case-sensitive `http` byte check.

**`src/image_fetch.py`** (line 140): `asyncio.timeout()` was added in Python 3.11, but `pyproject.toml` declares `requires-python = \">=3.10\"`. On Python 3.10 this raises `AttributeError: module 'asyncio' has no attribute 'timeout'`. Either bump the minimum to `>=3.11` in `pyproject.toml`, or replace with `asyncio.wait_for(_fetch_loop(url), timeout=FETCH_TIMEOUT)` which works on 3.10+.

**`tests/test_image_fetch.py`** (line 178): The `resolver` function (lines 178-181) is dead code — it is defined but never used. The test uses `fake_resolve` on line 183 instead. Remove the unused function.

**`tests/test_image_fetch.py`** (line 232): `asyncio.get_event_loop()` is deprecated in Python 3.12 and will emit a `DeprecationWarning`. Use `asyncio.get_running_loop()` instead — since this is an `async` test, a running loop is guaranteed.

**`src/proxy.py`** (line 186): The `b\"http\" in body` check is case-sensitive and would miss URLs with an uppercase scheme like `HTTP://example.com/a.png` (RFC 3986 says scheme is case-insensitive). The fallback is safe (body passes through unmodified), but consider `b\"http\" in body.lower()` or just accepting the trade-off with a comment.

**Review by foxpatch-aleph — COMMENTED** [review]
Well-architected SSRF-safe image fetcher with thorough test coverage (65 tests). The SSRF protections are solid: per-hop DNS re-resolution, public-IP validation with IPv4-mapped unwrap, SNI pinning, no keep-alive, magic-byte validation, size cap, and redirect limits. The cache/dedup logic using shielded futures is correct. The error taxonomy (400 for fetch failures, forward-unmodified for unexpected bugs) correctly addresses the original 503 failover problem. I have a few non-blocking observations around unbounded negative cache growth and missing edge-case tests.

**`src/image_fetch.py`** (line 210): The `_negative` dict has no size bound. A malicious user could trigger many distinct URL 404s (e.g., `https://x.test/{random}.png`) to grow `_negative` unboundedly between cleanup cycles. The cleanup on line 280 only purges expired entries when a *new* failure occurs, not proactively. Consider adding a cap (e.g., `len(_negative) > MAX_NEG_ENTRIES` eviction) or periodically sweeping expired entries.

**`src/image_fetch.py`** (line 280): Negative cache cleanup only happens inside the error branch of `_run_fetch`. If a URL was negatively cached (transient, 5s TTL) and the next request succeeds, the stale `_negative` entry is never removed — it just lingers until expiry. This is functionally benign (positive cache is checked first), but the negative dict can accumulate stale entries. Consider also removing the negative entry on success in `_run_fetch` (around line 305).

**`src/image_fetch.py`** (line 215): The `_stats` dict is maintained (hits, misses, evictions, neg_hits, coalesced) but never exposed in production — no metrics endpoint, no periodic log line. It's only useful in tests via `_reset_cache_for_tests`. If metrics aren't planned, this is dead tracking code; if they are, consider a periodic log or a `/metrics` dump.

**`src/proxy.py`** (line 197): The `except Exception` fallback (forward body unmodified) is not covered by a test. A test where `inline_remote_images` raises a non-HTTPException (e.g., `RuntimeError`) would verify the request still proceeds and the body is forwarded unchanged.

**`tests/test_image_fetch.py`** (line 410): Missing test for negative-cache TTL differentiation: verify that a transient failure (e.g., timeout) is cached for `NEG_CACHE_TTL_TRANSIENT` (5s) vs a deterministic failure (e.g., 404) for `NEG_CACHE_TTL_DETERMINISTIC` (60s). Also missing: a test that the `v1/completions` path is excluded from inlining (it's not in `IMAGE_INLINE_PATHS`).

**`pyproject.toml`** (line 55): Missing trailing newline at end of file.

**Review by foxpatch-aleph — COMMENTED** [review]
Well-engineered SSRF-safe image fetcher with thorough test coverage and a sound failure taxonomy. The SSRF defenses (DNS validation, IP pinning with SNI, per-redirect re-validation, no keep-alive, magic-byte type sniffing, size cap) are comprehensive. The detached asyncio.create_task at line 269 should save a strong reference per Python docs (low practical risk but documented footgun). The body.lower() guard on proxy.py:187 needfully copies the entire request body; a case-insensitive search or dual-check for b"http"/b"HTTP" would avoid the allocation. The double JSON parse on v1/chat/completions is harmless but wasteful for large payloads. No blocking issues found.

**`src/image_fetch.py`** (line 269): The Task returned by asyncio.create_task is not saved. Python docs warn: "Save a reference to the result of this function, to avoid a task disappearing mid-execution." In CPython 3.11 the event loop holds only a weak reference. The risk is low here because the task is always awaiting on I/O or the semaphore (which hold Task.__wakeup callbacks), but storing the task in a set and discarding on completion is the documented best practice.

**`src/proxy.py`** (line 187): body.lower() creates a full lowercase copy of the body bytes (potentially several MB for vision requests) just for a substring check. A cheaper alternative: b"http" in body or b"HTTP" in body, or use bytes.casefold() on a small window.

**`src/proxy.py`** (line 208): When images were inlined (image_changed=True), the body was just serialized on line 201 and is now re-parsed as JSON again for stream_options injection. Could reuse image_body_json when available to avoid the redundant serialize+deserialize cycle on large vision payloads.

**`src/image_fetch.py`** (line 292): The unexpected-exception path (non-ImageFetchError) doesn't write any negative cache entry, so a consistently-failing URL with an unexpected error will trigger a full fetch on every request. A very short negative TTL (e.g. 1s) would prevent a tight retry loop without poisoning the cache. Acceptable as-is but worth considering.

**`tests/test_proxy_image_inline.py`** (line 53): Integration tests verify the rewritten body content but don't assert that the stale Content-Length header was removed (proxy.py:202). Consider asserting captured headers to close this gap — if httpx didn't auto-recompute Content-Length, the upstream would receive a truncated body.

**Review by foxpatch-aleph — APPROVED** [review]
Well-engineered SSRF-safe image fetcher with robust caching, concurrency dedup, and correct failure taxonomy. The SSRF protections (DNS validation, IP pinning with SNI, per-redirect re-validation, magic-byte sniffing) are thorough. The concurrency model (inflight futures, shield+cancel, finally cleanup) is correct. Proxy integration is clean with single-parse/single-serialize and correct error handling (400 for fetch failures, forward-unmodified for unexpected bugs). The print->logger improvements are a bonus. Three minor non-blocking observations: (1) a mock signature mismatch in test_proxy_image_inline.py causes TypeError instead of the intended RuntimeError but the test still passes for the right reason, (2) expired positive cache entries aren't proactively purged (minor optimization), (3) no combined stream_options+inline test (pre-existing gap). Overall the code is production-ready and the 65-test suite provides excellent coverage.

**`tests/test_proxy_image_inline.py`** (line 121): The mock `boom(full_path, body_json)` has a signature mismatch with the real `inline_remote_images(body_json)` which takes a single argument. When called, this raises `TypeError: boom() missing 1 required positional argument` instead of the intended `RuntimeError`. The test still passes because both are caught by `except Exception` in proxy.py, but it's testing the wrong exception type. Fix: `async def boom(body_json):` — same issue at line 142 with `counting_inline`, though that mock is never called so it's harmless.

**`src/image_fetch.py`** (line 233): Expired positive cache entries are not proactively cleaned — they remain in `_positive` and count toward `_positive_bytes` until evicted by LRU pressure from new entries. Consider purging expired entries in `_cache_put` (similar to `_cache_negative`'s approach) to keep effective cache capacity closer to the 64MB target. Non-blocking optimization.

**Review by foxpatch-aleph — APPROVED** [review]
Well-engineered SSRF-safe image fetcher with robust caching, in-flight dedup, and a clean failure taxonomy that correctly maps fetch failures to 400 (preventing router failover cascades) while forwarding bodies unmodified on unexpected errors (never 500). The SSRF protection is thorough: all resolved IPs are validated, the socket is pinned to the validated IP with SNI preserved, and each redirect hop re-validates. Concurrency design with shielded futures, detached background tasks, and finally-guaranteed inflight cleanup is correct. Test coverage is comprehensive across SSRF, redirects, cache/dedup, all three API formats, and proxy integration. No blocking bugs or security issues found.

**`src/image_fetch.py`** (line 196): HTTP 429 (Too Many Requests) is classified as `transient=False` since `429 < 500`, giving it a 60s negative cache TTL. Given that 429 is the PR's stated root-cause scenario (wikimedia rate-limiting), it might warrant `transient=True` or a dedicated check like `transient=resp.status_code >= 500 or resp.status_code == 429`. The current 60s cache does prevent refetch storms, so this is a design tradeoff rather than a bug, but worth documenting the intent.

**`src/image_fetch.py`** (line 206): The `except HTTPException: raise` is load-bearing — without it, `HTTPException` (a subclass of `Exception`) would be caught by the `except Exception` on line 208 and swallowed, forwarding the body unmodified instead of returning a 400. A brief comment noting this would help future readers understand why the explicit re-raise can't be removed.

**`tests/test_image_fetch.py`** (line 413): Consider adding a test case for HTTP 429 specifically — given it's the root-cause scenario, asserting its transient classification (currently non-transient with 60s TTL) would document the intended behavior and catch regressions if the classification is later changed.

**Review by foxpatch-aleph — APPROVED** [review]
A well-crafted, security-conscious PR that solves the 503-on-remote-image-URL problem by fetching and inlining images at the gateway layer. The SSRF protections are thorough: DNS resolution with public-IP validation (including the IPv4-mapped IPv6 unwrap for Python 3.11.2), per-redirect-hop re-validation, IP-pinned sockets with SNI on the real hostname, 10MB size cap enforced mid-stream, magic-byte MIME sniffing, and no forwarding of caller auth headers. The caching layer (LRU with byte-bound eviction, split negative-cache TTLs, in-flight dedup) is correctly implemented with proper lock discipline. The failure taxonomy (fetch/validation failures → 400, unexpected bugs → forward unmodified) is the right design for the router's failover semantics. Test coverage is comprehensive at 65 tests covering SSRF vectors, redirect chains, cache eviction, concurrency, and all three API formats. The Python 3.10→3.11 bump is justified by asyncio.timeout usage. Minor observations below are non-blocking.

**`src/image_fetch.py`** (line 88): When a dict matches one of the image patterns, `stack.extend(obj.values())` still walks into the matched dict's values (e.g. `obj["image_url"]` for OpenAI chat format). This is harmless since the inner dict won't match any pattern, but it's slightly wasteful. Consider using `stack.extend(v for k, v in obj.items() if k != "image_url" and k != "source")` or simply documenting that the walk intentionally revisits nested structures.

**`src/image_fetch.py`** (line 337): If the `_run_fetch` task is cancelled while awaiting `_cache_lock` in this `finally` block, the `_inflight` cleanup on line 338-339 is skipped, potentially leaving a stale entry. The window is extremely small (the lock is held for trivial dict ops), but you could use a non-async cleanup (e.g. a plain dict pop without the lock) in the finally as a last resort, accepting the minor race on `_inflight` since it's only a dedup optimization.

**`src/image_fetch.py`** (line 173): Only `ips[0]` is used from the resolved addresses — if the first IP is down but another is healthy, there's no fallback. This is a reasonable design choice (the 10s timeout catches it as transient), but worth a comment noting the deliberate choice to avoid multi-IP retry complexity.

**`tests/test_image_fetch.py`** (line 21): The `_ImagePartFor` helper returns `url=""` for `openai_responses` and `anthropic` formats (where `image_url` is a string, not a dict). This doesn't affect `test_rewrite_each_format` since `_rewrite` ignores the `url` field, but it's a minor test smell — the helper silently produces a malformed `_ImagePart` for non-chat formats.

**`src/proxy.py`** (line 195): Switching from `json.loads(body)` to `await request.json()` is fine (Starlette caches the parsed body), but note that `request.json()` can also raise `TypeError` if the content-type header is missing in some Starlette versions. The current `except (json.JSONDecodeError, UnicodeDecodeError)` would not catch that. In practice FastAPI's pydantic parsing already consumed the body so `request.json()` returns the cached parse, making this a non-issue — but a defensive `except (json.JSONDecodeError, UnicodeDecodeError, TypeError)` would be safer.
